### ISSUE TITLE
HChaCha subkey example not updated

### ISSUE THREAD

**Issue by brycx** [bikeshedders/xchacha-rfc#10]
In commit 1e6a62a072d40960adf660c9e12b0939a64c974f the HChaCha state was updated but not the resulting subkey.

**Comment by paragonie-scott** [comment]
We corrected the byte order for the internal state, but the resulting subkey is not changed. That's why the "in little endian" remark was added before describing the final subkey.

**Comment by brycx** [comment]
I see, it must have been a mistake on my side after all. Apologies :)
