### ISSUE TITLE
Difference between XChaCha20 and AEAD_XChaCha20_Poly1305 encryption?

### ISSUE THREAD

**Issue by philanc** [bikeshedders/xchacha-rfc#12]
Looking at RFC 7539, I understand that that with *the same* parameters, the raw chacha20 and the aead construct create *the same* ciphertext (see the RFC, section 2.8.1)

If I understand correctly the xchacha-rfc draft section "2.3.1. XChaCha20 Pseudocode", and if as said in section "2. AEAD_XChaCha20_Poly1305" 
*"Use the subkey and remaining 8 bytes of the nonce (prefixed with 4 NUL bytes) with AEAD_CHACHA20_POLY1305 from [RFC7539] as normal"*,
I think that XChaCha20 and AEAD_XChaCha20_Poly1305 with the same parameters, should generate *the same* encrypted text.

If my point regarding the XChaCha20 test vector (issue #11) is wrong and the keystream/ciphertext  XChaCha20 and AEAD_XChaCha20_Poly1305 *are* different, some other implementers could face the same misunderstanding.

Then it would be good to have in the draft some more complete pseudo code of XChaCha20 and AEAD_XChaCha20_Poly1305 showing where the raw keystreams differ.

**Comment by philanc** [comment]
After a bit of investigation, it appears that the issue is the 'counter' parameter of chacha20_encrypt().

In RFC7539, the 'counter' parameter is explicit (as it is an input parameter of chacha20).  The tests vectors for chacha20 and for chacha20 in the AEAD construct both use (logically) the same counter=1

In the draft, the 'counter' does not appear in the section "2.3.1. XChaCha20 Pseudocode" (as I mentionned in issue #13).

The first test vector (AEAD construct) is computed with counter=1 (as requested in RFC7539)  by Sodium::crypto_aead_xchacha20poly1305_ietf_encrypt()

The second test vector is computed with counter=0  // *see note below*

I think that

1) **the counter value should be made explicit** as the key and IV already are.

2) for the sake of consistency with RFC7539, the draft shoud **use the same counter value** (1) for both  xchacha20 alone and chacha20 in the AEAD, as the RFC does.

--

[note]  This 2nd test vector is computed by ParagonIE_Sodium_Core_XChaCha20::streamXorIc($plaintext, $iv, $key).
I "think" streamXorIc() is defined  in https://github.com/paragonie/sodium_compat/blob/master/src/Core/XChaCha20.php and has a default `$ic=''` parameter. This default parameter is converted to `0` in  https://github.com/paragonie/sodium_compat/blob/master/src/Core/ChaCha20/Ctx.php*

If this is correct, it must be noted that this ChaCha20/Ctx.php implements the original Chacha20 (8-byte counter, 8-byte IV) and not the IETF Chacha20 (4-byte counter, 12-byte IV)  -  there should be no impact for the test vectors because the counter is little endian (and unlikely to go beyond 2^32!) and the first 4 bytes of IV are set to '00 00 00 00'  :wink:

**Comment by paragonie-scott** [comment]
> If this is correct, it must be noted that this ChaCha20/Ctx.php implements the original Chacha20 (8-byte counter, 8-byte IV) and not the IETF Chacha20 (4-byte counter, 12-byte IV) - there should be no impact for the test vectors because the counter is little endian (and unlikely to go beyond 2^32!) and the first 4 bytes of IV are set to '00 00 00 00' 😉

It actually uses ChaCha20/IetfCtx.php :)

Yeah, using explicit counters and, consistently, `c=1` is a better idea.

**Comment by philanc** [comment]
> It actually uses ChaCha20/IetfCtx.php :)

My mistake! I don't know PHP and probably got lost between Sodium and ParagonIE_Sodium_Compat and didn't find where things were coming from :)

**Comment by paragonie-scott** [comment]
It's okay. If you'd like to see what's happening here:

1. https://github.com/paragonie/sodium_compat/blob/5e280b50cdaf8da4cc4810e0847a9618be29703d/src/Core/ChaCha20.php#L335
2. https://github.com/paragonie/sodium_compat/blob/5e280b50cdaf8da4cc4810e0847a9618be29703d/src/Core/ChaCha20.php#L353

The IETF functions use a slightly different object (which really only differs in the constructor, but inherits from the base object you were inspecting).

**Comment by paragonie-scott** [comment]
https://github.com/bikeshedders/xchacha-rfc/commit/aa193cb156a8402d440b2eedc5af07c1a4453eeb implements your proposal. Is this satisfactory or should something else be changed too?

**Comment by paragonie-scott** [comment]
Ignore the .txt file in that commit, I forgot to run `build.sh` before committing.

**Comment by philanc** [comment]
> The IETF functions use a slightly different object (which really only differs in the constructor, but inherits from the base object you were inspecting).

but here, 
https://github.com/bikeshedders/xchacha-rfc/blob/8aed01f58c235880c3a809f096f22fb70e8772d2/test/test-vectors.php#L194
it calls streamXorIc(), not ietfStreamXorIc(), right? you even added an 8-byte counter :)

If I understand it, shouldn't it be

    ParagonIE_Sodium_Core_XChaCha20::ietfStreamXorIc($plaintext, $iv, $key, "\x01\x00\x00\x00");

?

**Comment by philanc** [comment]
> [aa193cb](https://github.com/bikeshedders/xchacha-rfc/commit/aa193cb156a8402d440b2eedc5af07c1a4453eeb) implements your proposal. Is this satisfactory or should something else be changed too?

    2.3.1.  XChaCha20 Pseudocode

         xchacha20_encrypt(key, nonce, plaintext):
            subkey = hchacha20(key, nonce[0:15])
            chacha20_nonce = "\x00\x00\x00\x00" + nonce[16:23]
            return chacha20_encrypt(subkey, 1, chacha20_nonce, plaintext)

Actually I think 'counter' should be an argument for  xchacha20_encrypt() as it is for chacha20_encrypt() in RFC7539 (and in the same order)

        xchacha20_encrypt(key, counter, nonce, plaintext):
            subkey = hchacha20(key, nonce[0:15])
            chacha20_nonce = "\x00\x00\x00\x00" + nonce[16:23]
            return chacha20_encrypt(subkey, counter, chacha20_nonce, plaintext)

For the AEAD construct, it is called with counter=1

    xchacha20_encrypt(key, 1, nonce, plaintext)

**Comment by paragonie-scott** [comment]
I added an XChaCha20 variant of `ietfStreamXorIc()` to sodium_compat in `v1.10.1`, since it was falling back to the ChaCha20 variant (which created "invalid nonce" exceptions).

The block counter changes you recommend have been implemented too.

You can see these changes here: https://tools.ietf.org/html/draft-irtf-cfrg-xchacha-00
