### ISSUE TITLE
RFC 7539 chacha20_encrypt arguments

### ISSUE THREAD

**Issue by philanc** [bikeshedders/xchacha-rfc#13]
Minor nitpick in section "2.3.1. XChaCha20 Pseudocode" regarding the line 

    return chacha20_encrypt(subkey, nonce[16:23], plaintext)

1) The RFC 7539 chacha20_encrypt function has a 'counter' argument that should be '1' for the construction.

2) the nonce should be prefixed with '00 00 00 00'

So the line could be changed to something like:

    chacha20_nonce = '00 00 00 00' | nonce[16:23]
    return chacha20_encrypt(subkey, 1, chacha20_nonce, plaintext)

**Comment by paragonie-scott** [comment]
Great suggestion! https://github.com/bikeshedders/xchacha-rfc/commit/8aed01f58c235880c3a809f096f22fb70e8772d2 implements that (and does a rebuild, which included some stuff in the .txt file my previous commit missed).
