### ISSUE TITLE
Add Test Vectors From Wycheproof?

### ISSUE THREAD

**Issue by paragonie-scott** [bikeshedders/xchacha-rfc#2]
Should any of the [possibly relevant Wycheproof test vectors](https://github.com/google/wycheproof/blob/master/testvectors/chacha20_poly1305_test.json) be used in our RFC?

**Comment by ValarDragon** [comment]
It may be simpler if this RFC just uses new test vectors. As far as I can tell, none of the Wycheproof test vectors apply to xchacha. (They all had 12 byte nonces)

**Comment by paragonie-scott** [comment]
I was thinking mostly of the edge cases and integer overflow tests, but they might be hard to replicate.

**Comment by LoupVaillant** [comment]
Chacha20, HChacha20, and XChacha20 are not subject to any special edge case involving integer overflow: addition is defined to be unsigned 32-bit modular addition (as implemented in C and all 32-bits processors), and there is no carry propagation.

Poly1305 *is* subject to subtle edge cases, but those are already covered by rfc7539. If this document means to use rfc7539 as a dependency, including those vectors is not necessary. If it means to stand on its own, it should define Poly1305 properly.

I believe this RFC means to lean on rfc7539.
