### ISSUE TITLE
Proper links for Monocypher

### ISSUE THREAD

**Issue by LoupVaillant** [bikeshedders/xchacha-rfc#5]
Thanks for mentioning Monocypher, that's a nice bit of recognition.

On line 85 of the [markdow version](https://github.com/bikeshedders/xchacha-rfc/blob/master/xchacha.md), (and line 323 of the [txt version](https://github.com/bikeshedders/xchacha-rfc/blob/master/draft-arciszewski-xchacha-rfc-00.txt#L323)), Monocypher is referred to by its GitHub repository.

To avoid link rot, I suggest not linking to GitHub. It is merely a mirror, and may go down without notice. The official site is [https://monocypher.org](). If you want to point directly to the relevant manual page (as you did for Libsodium), you may use [https://monocypher.org/manual/aead]() instead.

**Comment by paragonie-scott** [comment]
Ironically, your bare link hyperlinks to this issue. Fixing ASAP.

https://monocypher.org/manual/aead

**Comment by paragonie-scott** [comment]
Fixed in https://github.com/bikeshedders/xchacha-rfc/commit/43d164d3fa67f91599cc8e1c5462f426d4a329cd

**Comment by LoupVaillant** [comment]
Nice, thanks!
