### ISSUE TITLE
Incorrect test vector

### ISSUE THREAD

**Issue by vkrasnov** [bikeshedders/xchacha-rfc#6]
```
000 40 41 42 43 44 45 46 47 48 49 4a fb 4c 4d 4e 4f  @ABCDEFGHIJKLMNO
             Should be 4b and not fb^^^
```

Should be 4b and not fb.

**Comment by paragonie-scott** [comment]
Thanks! 👍 

This was fixed in https://github.com/bikeshedders/xchacha-rfc/commit/95bd86c0d943caaa73f4f64f49a76a07fcfd0046

I included a verification script in https://github.com/bikeshedders/xchacha-rfc/commit/25eba62263bffbab229a8da1d19505e86f1da307 as well.
