### ISSUE TITLE
Incorrect test vector for HChaCha20 block function

### ISSUE THREAD

**Issue by brycx** [bikeshedders/xchacha-rfc#7]
I believe there is an incorrect `2` and `5` in the below test vector, marked with ().

```
82413b4 (2)27b27bfe d30e4250 8a877d73
a0f9e4d (5)8a74a853 c12ec413 26d3ecdc

Resultant HChaCha20 subkey
```
The following makes it the same as the expected HChaCha state after 20 rounds.
```
82413b42 27b27bfe d30e4250 8a877d73
a0f9e4d5 8a74a853 c12ec413 26d3ecdc
```

**Comment by paragonie-scott** [comment]
Thanks! 👍 

The issue was with where the whitespace was inserted. https://github.com/bikeshedders/xchacha-rfc/commit/5873f6965fbee12c822c4ced9732daf79c25d273
