### ISSUE TITLE
HPolyC doesn't use "XChaCha12-Poly1305"

### ISSUE THREAD

**Issue by ebiggers** [bikeshedders/xchacha-rfc#8]
The RFC says

> Similarly, Google's HPolyC [10] implements XChaCha12-Poly1305.

HPolyC is a length-preserving mode that uses XChaCha12, the Poly1305 ε-almost-∆-universal hash function, and a block cipher.  It doesn't use the full Poly1305 MAC, nor does it use an AEAD.  But "XChaCha12-Poly1305" implies the AEAD.  Perhaps just say that HPolyC "uses XChaCha12"?

**Comment by paragonie-scott** [comment]
Good catch. I'll correct that immediately.

Thanks for taking the time to review the RFC draft and share your feedback.
